// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface AlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.Alert)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<Alert> {

  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  java.util.List<com.google.transit.realtime.TimeRange> 
      getActivePeriodList();
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  com.google.transit.realtime.TimeRange getActivePeriod(int index);
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  int getActivePeriodCount();
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  java.util.List<? extends com.google.transit.realtime.TimeRangeOrBuilder> 
      getActivePeriodOrBuilderList();
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  com.google.transit.realtime.TimeRangeOrBuilder getActivePeriodOrBuilder(
      int index);

  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  java.util.List<com.google.transit.realtime.EntitySelector> 
      getInformedEntityList();
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  com.google.transit.realtime.EntitySelector getInformedEntity(int index);
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  int getInformedEntityCount();
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  java.util.List<? extends com.google.transit.realtime.EntitySelectorOrBuilder> 
      getInformedEntityOrBuilderList();
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  com.google.transit.realtime.EntitySelectorOrBuilder getInformedEntityOrBuilder(
      int index);

  /**
   * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
   * @return Whether the cause field is set.
   */
  boolean hasCause();
  /**
   * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
   * @return The cause.
   */
  com.google.transit.realtime.Alert.Cause getCause();

  /**
   * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
   * @return Whether the effect field is set.
   */
  boolean hasEffect();
  /**
   * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
   * @return The effect.
   */
  com.google.transit.realtime.Alert.Effect getEffect();

  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   * @return The url.
   */
  com.google.transit.realtime.TranslatedString getUrl();
  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getUrlOrBuilder();

  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   * @return Whether the headerText field is set.
   */
  boolean hasHeaderText();
  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   * @return The headerText.
   */
  com.google.transit.realtime.TranslatedString getHeaderText();
  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getHeaderTextOrBuilder();

  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   * @return Whether the descriptionText field is set.
   */
  boolean hasDescriptionText();
  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   * @return The descriptionText.
   */
  com.google.transit.realtime.TranslatedString getDescriptionText();
  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getDescriptionTextOrBuilder();

  /**
   * <pre>
   * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
   * @return Whether the ttsHeaderText field is set.
   */
  boolean hasTtsHeaderText();
  /**
   * <pre>
   * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
   * @return The ttsHeaderText.
   */
  com.google.transit.realtime.TranslatedString getTtsHeaderText();
  /**
   * <pre>
   * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_header_text = 12;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getTtsHeaderTextOrBuilder();

  /**
   * <pre>
   * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
   * @return Whether the ttsDescriptionText field is set.
   */
  boolean hasTtsDescriptionText();
  /**
   * <pre>
   * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
   * @return The ttsDescriptionText.
   */
  com.google.transit.realtime.TranslatedString getTtsDescriptionText();
  /**
   * <pre>
   * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString tts_description_text = 13;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getTtsDescriptionTextOrBuilder();

  /**
   * <code>optional .transit_realtime.Alert.SeverityLevel severity_level = 14 [default = UNKNOWN_SEVERITY];</code>
   * @return Whether the severityLevel field is set.
   */
  boolean hasSeverityLevel();
  /**
   * <code>optional .transit_realtime.Alert.SeverityLevel severity_level = 14 [default = UNKNOWN_SEVERITY];</code>
   * @return The severityLevel.
   */
  com.google.transit.realtime.Alert.SeverityLevel getSeverityLevel();

  /**
   * <pre>
   * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
   * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedImage image = 15;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <pre>
   * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
   * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedImage image = 15;</code>
   * @return The image.
   */
  com.google.transit.realtime.TranslatedImage getImage();
  /**
   * <pre>
   * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
   * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information. 
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedImage image = 15;</code>
   */
  com.google.transit.realtime.TranslatedImageOrBuilder getImageOrBuilder();

  /**
   * <pre>
   * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
   * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
   * @return Whether the imageAlternativeText field is set.
   */
  boolean hasImageAlternativeText();
  /**
   * <pre>
   * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
   * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
   * @return The imageAlternativeText.
   */
  com.google.transit.realtime.TranslatedString getImageAlternativeText();
  /**
   * <pre>
   * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
   * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString image_alternative_text = 16;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getImageAlternativeTextOrBuilder();

  /**
   * <pre>
   * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
   * @return Whether the causeDetail field is set.
   */
  boolean hasCauseDetail();
  /**
   * <pre>
   * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
   * @return The causeDetail.
   */
  com.google.transit.realtime.TranslatedString getCauseDetail();
  /**
   * <pre>
   * Description of the cause of the alert that allows for agency-specific language; more specific than the Cause. If cause_detail is included, then Cause must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString cause_detail = 17;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getCauseDetailOrBuilder();

  /**
   * <pre>
   * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
   * @return Whether the effectDetail field is set.
   */
  boolean hasEffectDetail();
  /**
   * <pre>
   * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
   * @return The effectDetail.
   */
  com.google.transit.realtime.TranslatedString getEffectDetail();
  /**
   * <pre>
   * Description of the effect of the alert that allows for agency-specific language; more specific than the Effect. If effect_detail is included, then Effect must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString effect_detail = 18;</code>
   */
  com.google.transit.realtime.TranslatedStringOrBuilder getEffectDetailOrBuilder();
}
