// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface EntitySelectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.EntitySelector)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<EntitySelector> {

  /**
   * <pre>
   * The values of the fields should correspond to the appropriate fields in the
   * GTFS feed.
   * At least one specifier must be given. If several are given, then the
   * matching has to apply to all the given specifiers.
   * </pre>
   *
   * <code>optional string agency_id = 1;</code>
   * @return Whether the agencyId field is set.
   */
  boolean hasAgencyId();
  /**
   * <pre>
   * The values of the fields should correspond to the appropriate fields in the
   * GTFS feed.
   * At least one specifier must be given. If several are given, then the
   * matching has to apply to all the given specifiers.
   * </pre>
   *
   * <code>optional string agency_id = 1;</code>
   * @return The agencyId.
   */
  java.lang.String getAgencyId();
  /**
   * <pre>
   * The values of the fields should correspond to the appropriate fields in the
   * GTFS feed.
   * At least one specifier must be given. If several are given, then the
   * matching has to apply to all the given specifiers.
   * </pre>
   *
   * <code>optional string agency_id = 1;</code>
   * @return The bytes for agencyId.
   */
  com.google.protobuf.ByteString
      getAgencyIdBytes();

  /**
   * <code>optional string route_id = 2;</code>
   * @return Whether the routeId field is set.
   */
  boolean hasRouteId();
  /**
   * <code>optional string route_id = 2;</code>
   * @return The routeId.
   */
  java.lang.String getRouteId();
  /**
   * <code>optional string route_id = 2;</code>
   * @return The bytes for routeId.
   */
  com.google.protobuf.ByteString
      getRouteIdBytes();

  /**
   * <pre>
   * corresponds to route_type in GTFS.
   * </pre>
   *
   * <code>optional int32 route_type = 3;</code>
   * @return Whether the routeType field is set.
   */
  boolean hasRouteType();
  /**
   * <pre>
   * corresponds to route_type in GTFS.
   * </pre>
   *
   * <code>optional int32 route_type = 3;</code>
   * @return The routeType.
   */
  int getRouteType();

  /**
   * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
   * @return Whether the trip field is set.
   */
  boolean hasTrip();
  /**
   * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
   * @return The trip.
   */
  com.google.transit.realtime.TripDescriptor getTrip();
  /**
   * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
   */
  com.google.transit.realtime.TripDescriptorOrBuilder getTripOrBuilder();

  /**
   * <code>optional string stop_id = 5;</code>
   * @return Whether the stopId field is set.
   */
  boolean hasStopId();
  /**
   * <code>optional string stop_id = 5;</code>
   * @return The stopId.
   */
  java.lang.String getStopId();
  /**
   * <code>optional string stop_id = 5;</code>
   * @return The bytes for stopId.
   */
  com.google.protobuf.ByteString
      getStopIdBytes();

  /**
   * <pre>
   * Corresponds to trip direction_id in GTFS trips.txt. If provided the
   * route_id must also be provided.
   * </pre>
   *
   * <code>optional uint32 direction_id = 6;</code>
   * @return Whether the directionId field is set.
   */
  boolean hasDirectionId();
  /**
   * <pre>
   * Corresponds to trip direction_id in GTFS trips.txt. If provided the
   * route_id must also be provided.
   * </pre>
   *
   * <code>optional uint32 direction_id = 6;</code>
   * @return The directionId.
   */
  int getDirectionId();
}
