// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface FeedHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.FeedHeader)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<FeedHeader> {

  /**
   * <pre>
   * Version of the feed specification.
   * The current version is 2.0.  Valid versions are "2.0", "1.0".
   * </pre>
   *
   * <code>required string gtfs_realtime_version = 1;</code>
   * @return Whether the gtfsRealtimeVersion field is set.
   */
  boolean hasGtfsRealtimeVersion();
  /**
   * <pre>
   * Version of the feed specification.
   * The current version is 2.0.  Valid versions are "2.0", "1.0".
   * </pre>
   *
   * <code>required string gtfs_realtime_version = 1;</code>
   * @return The gtfsRealtimeVersion.
   */
  java.lang.String getGtfsRealtimeVersion();
  /**
   * <pre>
   * Version of the feed specification.
   * The current version is 2.0.  Valid versions are "2.0", "1.0".
   * </pre>
   *
   * <code>required string gtfs_realtime_version = 1;</code>
   * @return The bytes for gtfsRealtimeVersion.
   */
  com.google.protobuf.ByteString
      getGtfsRealtimeVersionBytes();

  /**
   * <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2 [default = FULL_DATASET];</code>
   * @return Whether the incrementality field is set.
   */
  boolean hasIncrementality();
  /**
   * <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2 [default = FULL_DATASET];</code>
   * @return The incrementality.
   */
  com.google.transit.realtime.FeedHeader.Incrementality getIncrementality();

  /**
   * <pre>
   * This timestamp identifies the moment when the content of this feed has been
   * created (in server time). In POSIX time (i.e., number of seconds since
   * January 1st 1970 00:00:00 UTC).
   * </pre>
   *
   * <code>optional uint64 timestamp = 3;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * This timestamp identifies the moment when the content of this feed has been
   * created (in server time). In POSIX time (i.e., number of seconds since
   * January 1st 1970 00:00:00 UTC).
   * </pre>
   *
   * <code>optional uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
