// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public final class GtfsRealtime {
  private GtfsRealtime() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_FeedEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_FeedEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripUpdate_StopTimeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripUpdate_StopTimeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripUpdate_TripProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripUpdate_TripProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_VehiclePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_VehiclePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_VehiclePosition_CarriageDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_VehiclePosition_CarriageDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TimeRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TimeRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TripDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TripDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_VehicleDescriptor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_EntitySelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_EntitySelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TranslatedString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TranslatedString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TranslatedString_Translation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TranslatedImage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TranslatedImage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_TranslatedImage_LocalizedImage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_Shape_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_Shape_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"main/resources/gtfs-realtime.proto\022\020tr" +
      "ansit_realtime\"y\n\013FeedMessage\022,\n\006header\030" +
      "\001 \002(\0132\034.transit_realtime.FeedHeader\022,\n\006e" +
      "ntity\030\002 \003(\0132\034.transit_realtime.FeedEntit" +
      "y*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\327\001\n\nFeedHeader\022\035\n\025gtfs" +
      "_realtime_version\030\001 \002(\t\022Q\n\016incrementalit" +
      "y\030\002 \001(\0162+.transit_realtime.FeedHeader.In" +
      "crementality:\014FULL_DATASET\022\021\n\ttimestamp\030" +
      "\003 \001(\004\"4\n\016Incrementality\022\020\n\014FULL_DATASET\020" +
      "\000\022\020\n\014DIFFERENTIAL\020\001*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\372\001\n\n" +
      "FeedEntity\022\n\n\002id\030\001 \002(\t\022\031\n\nis_deleted\030\002 \001" +
      "(\010:\005false\0221\n\013trip_update\030\003 \001(\0132\034.transit" +
      "_realtime.TripUpdate\0222\n\007vehicle\030\004 \001(\0132!." +
      "transit_realtime.VehiclePosition\022&\n\005aler" +
      "t\030\005 \001(\0132\027.transit_realtime.Alert\022&\n\005shap" +
      "e\030\006 \001(\0132\027.transit_realtime.Shape*\006\010\350\007\020\320\017" +
      "*\006\010\250F\020\220N\"\353\010\n\nTripUpdate\022.\n\004trip\030\001 \002(\0132 ." +
      "transit_realtime.TripDescriptor\0224\n\007vehic" +
      "le\030\003 \001(\0132#.transit_realtime.VehicleDescr" +
      "iptor\022E\n\020stop_time_update\030\002 \003(\0132+.transi" +
      "t_realtime.TripUpdate.StopTimeUpdate\022\021\n\t" +
      "timestamp\030\004 \001(\004\022\r\n\005delay\030\005 \001(\005\022D\n\017trip_p" +
      "roperties\030\006 \001(\0132+.transit_realtime.TripU" +
      "pdate.TripProperties\032Q\n\rStopTimeEvent\022\r\n" +
      "\005delay\030\001 \001(\005\022\014\n\004time\030\002 \001(\003\022\023\n\013uncertaint" +
      "y\030\003 \001(\005*\006\010\350\007\020\320\017*\006\010\250F\020\220N\032\367\004\n\016StopTimeUpda" +
      "te\022\025\n\rstop_sequence\030\001 \001(\r\022\017\n\007stop_id\030\004 \001" +
      "(\t\022;\n\007arrival\030\002 \001(\0132*.transit_realtime.T" +
      "ripUpdate.StopTimeEvent\022=\n\tdeparture\030\003 \001" +
      "(\0132*.transit_realtime.TripUpdate.StopTim" +
      "eEvent\022U\n\032departure_occupancy_status\030\007 \001" +
      "(\01621.transit_realtime.VehiclePosition.Oc" +
      "cupancyStatus\022j\n\025schedule_relationship\030\005" +
      " \001(\0162@.transit_realtime.TripUpdate.StopT" +
      "imeUpdate.ScheduleRelationship:\tSCHEDULE" +
      "D\022\\\n\024stop_time_properties\030\006 \001(\0132>.transi" +
      "t_realtime.TripUpdate.StopTimeUpdate.Sto" +
      "pTimeProperties\032>\n\022StopTimeProperties\022\030\n" +
      "\020assigned_stop_id\030\001 \001(\t*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"" +
      "P\n\024ScheduleRelationship\022\r\n\tSCHEDULED\020\000\022\013" +
      "\n\007SKIPPED\020\001\022\013\n\007NO_DATA\020\002\022\017\n\013UNSCHEDULED\020" +
      "\003*\006\010\350\007\020\320\017*\006\010\250F\020\220N\032k\n\016TripProperties\022\017\n\007t" +
      "rip_id\030\001 \001(\t\022\022\n\nstart_date\030\002 \001(\t\022\022\n\nstar" +
      "t_time\030\003 \001(\t\022\020\n\010shape_id\030\004 \001(\t*\006\010\350\007\020\320\017*\006" +
      "\010\250F\020\220N*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\337\t\n\017VehiclePositi" +
      "on\022.\n\004trip\030\001 \001(\0132 .transit_realtime.Trip" +
      "Descriptor\0224\n\007vehicle\030\010 \001(\0132#.transit_re" +
      "altime.VehicleDescriptor\022,\n\010position\030\002 \001" +
      "(\0132\032.transit_realtime.Position\022\035\n\025curren" +
      "t_stop_sequence\030\003 \001(\r\022\017\n\007stop_id\030\007 \001(\t\022Z" +
      "\n\016current_status\030\004 \001(\01623.transit_realtim" +
      "e.VehiclePosition.VehicleStopStatus:\rIN_" +
      "TRANSIT_TO\022\021\n\ttimestamp\030\005 \001(\004\022K\n\020congest" +
      "ion_level\030\006 \001(\01621.transit_realtime.Vehic" +
      "lePosition.CongestionLevel\022K\n\020occupancy_" +
      "status\030\t \001(\01621.transit_realtime.VehicleP" +
      "osition.OccupancyStatus\022\034\n\024occupancy_per" +
      "centage\030\n \001(\r\022Q\n\026multi_carriage_details\030" +
      "\013 \003(\01321.transit_realtime.VehiclePosition" +
      ".CarriageDetails\032\331\001\n\017CarriageDetails\022\n\n\002" +
      "id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022^\n\020occupancy_sta" +
      "tus\030\003 \001(\01621.transit_realtime.VehiclePosi" +
      "tion.OccupancyStatus:\021NO_DATA_AVAILABLE\022" +
      " \n\024occupancy_percentage\030\004 \001(\005:\002-1\022\031\n\021car" +
      "riage_sequence\030\005 \001(\r*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"G\n\021" +
      "VehicleStopStatus\022\017\n\013INCOMING_AT\020\000\022\016\n\nST" +
      "OPPED_AT\020\001\022\021\n\rIN_TRANSIT_TO\020\002\"}\n\017Congest" +
      "ionLevel\022\034\n\030UNKNOWN_CONGESTION_LEVEL\020\000\022\024" +
      "\n\020RUNNING_SMOOTHLY\020\001\022\017\n\013STOP_AND_GO\020\002\022\016\n" +
      "\nCONGESTION\020\003\022\025\n\021SEVERE_CONGESTION\020\004\"\331\001\n" +
      "\017OccupancyStatus\022\t\n\005EMPTY\020\000\022\030\n\024MANY_SEAT" +
      "S_AVAILABLE\020\001\022\027\n\023FEW_SEATS_AVAILABLE\020\002\022\026" +
      "\n\022STANDING_ROOM_ONLY\020\003\022\036\n\032CRUSHED_STANDI" +
      "NG_ROOM_ONLY\020\004\022\010\n\004FULL\020\005\022\034\n\030NOT_ACCEPTIN" +
      "G_PASSENGERS\020\006\022\025\n\021NO_DATA_AVAILABLE\020\007\022\021\n" +
      "\rNOT_BOARDABLE\020\010*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\353\n\n\005Ale" +
      "rt\0222\n\ractive_period\030\001 \003(\0132\033.transit_real" +
      "time.TimeRange\0229\n\017informed_entity\030\005 \003(\0132" +
      " .transit_realtime.EntitySelector\022;\n\005cau" +
      "se\030\006 \001(\0162\035.transit_realtime.Alert.Cause:" +
      "\rUNKNOWN_CAUSE\022>\n\006effect\030\007 \001(\0162\036.transit" +
      "_realtime.Alert.Effect:\016UNKNOWN_EFFECT\022/" +
      "\n\003url\030\010 \001(\0132\".transit_realtime.Translate" +
      "dString\0227\n\013header_text\030\n \001(\0132\".transit_r" +
      "ealtime.TranslatedString\022<\n\020description_" +
      "text\030\013 \001(\0132\".transit_realtime.Translated" +
      "String\022;\n\017tts_header_text\030\014 \001(\0132\".transi" +
      "t_realtime.TranslatedString\022@\n\024tts_descr" +
      "iption_text\030\r \001(\0132\".transit_realtime.Tra" +
      "nslatedString\022O\n\016severity_level\030\016 \001(\0162%." +
      "transit_realtime.Alert.SeverityLevel:\020UN" +
      "KNOWN_SEVERITY\0220\n\005image\030\017 \001(\0132!.transit_" +
      "realtime.TranslatedImage\022B\n\026image_altern" +
      "ative_text\030\020 \001(\0132\".transit_realtime.Tran" +
      "slatedString\0228\n\014cause_detail\030\021 \001(\0132\".tra" +
      "nsit_realtime.TranslatedString\0229\n\reffect" +
      "_detail\030\022 \001(\0132\".transit_realtime.Transla" +
      "tedString\"\330\001\n\005Cause\022\021\n\rUNKNOWN_CAUSE\020\001\022\017" +
      "\n\013OTHER_CAUSE\020\002\022\025\n\021TECHNICAL_PROBLEM\020\003\022\n" +
      "\n\006STRIKE\020\004\022\021\n\rDEMONSTRATION\020\005\022\014\n\010ACCIDEN" +
      "T\020\006\022\013\n\007HOLIDAY\020\007\022\013\n\007WEATHER\020\010\022\017\n\013MAINTEN" +
      "ANCE\020\t\022\020\n\014CONSTRUCTION\020\n\022\023\n\017POLICE_ACTIV" +
      "ITY\020\013\022\025\n\021MEDICAL_EMERGENCY\020\014\"\335\001\n\006Effect\022" +
      "\016\n\nNO_SERVICE\020\001\022\023\n\017REDUCED_SERVICE\020\002\022\026\n\022" +
      "SIGNIFICANT_DELAYS\020\003\022\n\n\006DETOUR\020\004\022\026\n\022ADDI" +
      "TIONAL_SERVICE\020\005\022\024\n\020MODIFIED_SERVICE\020\006\022\020" +
      "\n\014OTHER_EFFECT\020\007\022\022\n\016UNKNOWN_EFFECT\020\010\022\016\n\n" +
      "STOP_MOVED\020\t\022\r\n\tNO_EFFECT\020\n\022\027\n\023ACCESSIBI" +
      "LITY_ISSUE\020\013\"H\n\rSeverityLevel\022\024\n\020UNKNOWN" +
      "_SEVERITY\020\001\022\010\n\004INFO\020\002\022\013\n\007WARNING\020\003\022\n\n\006SE" +
      "VERE\020\004*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"7\n\tTimeRange\022\r\n\005s" +
      "tart\030\001 \001(\004\022\013\n\003end\030\002 \001(\004*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"" +
      "q\n\010Position\022\020\n\010latitude\030\001 \002(\002\022\021\n\tlongitu" +
      "de\030\002 \002(\002\022\017\n\007bearing\030\003 \001(\002\022\020\n\010odometer\030\004 " +
      "\001(\001\022\r\n\005speed\030\005 \001(\002*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\333\002\n\016T" +
      "ripDescriptor\022\017\n\007trip_id\030\001 \001(\t\022\020\n\010route_" +
      "id\030\005 \001(\t\022\024\n\014direction_id\030\006 \001(\r\022\022\n\nstart_" +
      "time\030\002 \001(\t\022\022\n\nstart_date\030\003 \001(\t\022T\n\025schedu" +
      "le_relationship\030\004 \001(\01625.transit_realtime" +
      ".TripDescriptor.ScheduleRelationship\"\201\001\n" +
      "\024ScheduleRelationship\022\r\n\tSCHEDULED\020\000\022\t\n\005" +
      "ADDED\020\001\022\017\n\013UNSCHEDULED\020\002\022\014\n\010CANCELED\020\003\022\023" +
      "\n\013REPLACEMENT\020\005\032\002\010\001\022\016\n\nDUPLICATED\020\006\022\013\n\007D" +
      "ELETED\020\007*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\243\002\n\021VehicleDesc" +
      "riptor\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\022\025\n\rlic" +
      "ense_plate\030\003 \001(\t\022a\n\025wheelchair_accessibl" +
      "e\030\004 \001(\01628.transit_realtime.VehicleDescri" +
      "ptor.WheelchairAccessible:\010NO_VALUE\"i\n\024W" +
      "heelchairAccessible\022\014\n\010NO_VALUE\020\000\022\013\n\007UNK" +
      "NOWN\020\001\022\031\n\025WHEELCHAIR_ACCESSIBLE\020\002\022\033\n\027WHE" +
      "ELCHAIR_INACCESSIBLE\020\003*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\260" +
      "\001\n\016EntitySelector\022\021\n\tagency_id\030\001 \001(\t\022\020\n\010" +
      "route_id\030\002 \001(\t\022\022\n\nroute_type\030\003 \001(\005\022.\n\004tr" +
      "ip\030\004 \001(\0132 .transit_realtime.TripDescript" +
      "or\022\017\n\007stop_id\030\005 \001(\t\022\024\n\014direction_id\030\006 \001(" +
      "\r*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\246\001\n\020TranslatedString\022C" +
      "\n\013translation\030\001 \003(\0132..transit_realtime.T" +
      "ranslatedString.Translation\032=\n\013Translati" +
      "on\022\014\n\004text\030\001 \002(\t\022\020\n\010language\030\002 \001(\t*\006\010\350\007\020" +
      "\320\017*\006\010\250F\020\220N*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"\301\001\n\017Translate" +
      "dImage\022I\n\017localized_image\030\001 \003(\01320.transi" +
      "t_realtime.TranslatedImage.LocalizedImag" +
      "e\032S\n\016LocalizedImage\022\013\n\003url\030\001 \002(\t\022\022\n\nmedi" +
      "a_type\030\002 \002(\t\022\020\n\010language\030\003 \001(\t*\006\010\350\007\020\320\017*\006" +
      "\010\250F\020\220N*\006\010\350\007\020\320\017*\006\010\250F\020\220N\"C\n\005Shape\022\020\n\010shape" +
      "_id\030\001 \001(\t\022\030\n\020encoded_polyline\030\002 \001(\t*\006\010\350\007" +
      "\020\320\017*\006\010\250F\020\220NB\037\n\033com.google.transit.realti" +
      "meP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transit_realtime_FeedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_FeedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedMessage_descriptor,
        new java.lang.String[] { "Header", "Entity", });
    internal_static_transit_realtime_FeedHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transit_realtime_FeedHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedHeader_descriptor,
        new java.lang.String[] { "GtfsRealtimeVersion", "Incrementality", "Timestamp", });
    internal_static_transit_realtime_FeedEntity_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transit_realtime_FeedEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_FeedEntity_descriptor,
        new java.lang.String[] { "Id", "IsDeleted", "TripUpdate", "Vehicle", "Alert", "Shape", });
    internal_static_transit_realtime_TripUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transit_realtime_TripUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripUpdate_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "StopTimeUpdate", "Timestamp", "Delay", "TripProperties", });
    internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor =
      internal_static_transit_realtime_TripUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_TripUpdate_StopTimeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor,
        new java.lang.String[] { "Delay", "Time", "Uncertainty", });
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor =
      internal_static_transit_realtime_TripUpdate_descriptor.getNestedTypes().get(1);
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor,
        new java.lang.String[] { "StopSequence", "StopId", "Arrival", "Departure", "DepartureOccupancyStatus", "ScheduleRelationship", "StopTimeProperties", });
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties_descriptor =
      internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties_descriptor,
        new java.lang.String[] { "AssignedStopId", });
    internal_static_transit_realtime_TripUpdate_TripProperties_descriptor =
      internal_static_transit_realtime_TripUpdate_descriptor.getNestedTypes().get(2);
    internal_static_transit_realtime_TripUpdate_TripProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripUpdate_TripProperties_descriptor,
        new java.lang.String[] { "TripId", "StartDate", "StartTime", "ShapeId", });
    internal_static_transit_realtime_VehiclePosition_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transit_realtime_VehiclePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_VehiclePosition_descriptor,
        new java.lang.String[] { "Trip", "Vehicle", "Position", "CurrentStopSequence", "StopId", "CurrentStatus", "Timestamp", "CongestionLevel", "OccupancyStatus", "OccupancyPercentage", "MultiCarriageDetails", });
    internal_static_transit_realtime_VehiclePosition_CarriageDetails_descriptor =
      internal_static_transit_realtime_VehiclePosition_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_VehiclePosition_CarriageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_VehiclePosition_CarriageDetails_descriptor,
        new java.lang.String[] { "Id", "Label", "OccupancyStatus", "OccupancyPercentage", "CarriageSequence", });
    internal_static_transit_realtime_Alert_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transit_realtime_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_Alert_descriptor,
        new java.lang.String[] { "ActivePeriod", "InformedEntity", "Cause", "Effect", "Url", "HeaderText", "DescriptionText", "TtsHeaderText", "TtsDescriptionText", "SeverityLevel", "Image", "ImageAlternativeText", "CauseDetail", "EffectDetail", });
    internal_static_transit_realtime_TimeRange_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_transit_realtime_TimeRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TimeRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_transit_realtime_Position_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_transit_realtime_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_Position_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Bearing", "Odometer", "Speed", });
    internal_static_transit_realtime_TripDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_transit_realtime_TripDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TripDescriptor_descriptor,
        new java.lang.String[] { "TripId", "RouteId", "DirectionId", "StartTime", "StartDate", "ScheduleRelationship", });
    internal_static_transit_realtime_VehicleDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_VehicleDescriptor_descriptor,
        new java.lang.String[] { "Id", "Label", "LicensePlate", "WheelchairAccessible", });
    internal_static_transit_realtime_EntitySelector_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_transit_realtime_EntitySelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_EntitySelector_descriptor,
        new java.lang.String[] { "AgencyId", "RouteId", "RouteType", "Trip", "StopId", "DirectionId", });
    internal_static_transit_realtime_TranslatedString_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_transit_realtime_TranslatedString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TranslatedString_descriptor,
        new java.lang.String[] { "Translation", });
    internal_static_transit_realtime_TranslatedString_Translation_descriptor =
      internal_static_transit_realtime_TranslatedString_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TranslatedString_Translation_descriptor,
        new java.lang.String[] { "Text", "Language", });
    internal_static_transit_realtime_TranslatedImage_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_transit_realtime_TranslatedImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TranslatedImage_descriptor,
        new java.lang.String[] { "LocalizedImage", });
    internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor =
      internal_static_transit_realtime_TranslatedImage_descriptor.getNestedTypes().get(0);
    internal_static_transit_realtime_TranslatedImage_LocalizedImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor,
        new java.lang.String[] { "Url", "MediaType", "Language", });
    internal_static_transit_realtime_Shape_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_transit_realtime_Shape_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_Shape_descriptor,
        new java.lang.String[] { "ShapeId", "EncodedPolyline", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
