// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface TimeRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.TimeRange)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<TimeRange> {

  /**
   * <pre>
   * Start time, in POSIX time (i.e., number of seconds since January 1st 1970
   * 00:00:00 UTC).
   * If missing, the interval starts at minus infinity.
   * </pre>
   *
   * <code>optional uint64 start = 1;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <pre>
   * Start time, in POSIX time (i.e., number of seconds since January 1st 1970
   * 00:00:00 UTC).
   * If missing, the interval starts at minus infinity.
   * </pre>
   *
   * <code>optional uint64 start = 1;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <pre>
   * End time, in POSIX time (i.e., number of seconds since January 1st 1970
   * 00:00:00 UTC).
   * If missing, the interval ends at plus infinity.
   * </pre>
   *
   * <code>optional uint64 end = 2;</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <pre>
   * End time, in POSIX time (i.e., number of seconds since January 1st 1970
   * 00:00:00 UTC).
   * If missing, the interval ends at plus infinity.
   * </pre>
   *
   * <code>optional uint64 end = 2;</code>
   * @return The end.
   */
  long getEnd();
}
