// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

/**
 * <pre>
 * An internationalized image containing per-language versions of a URL linking to an image
 * along with meta information
 * Only one of the images from a message will be retained by consumers. The resolution proceeds
 * as follows:
 * 1. If the UI language matches the language code of a translation,
 *    the first matching translation is picked.
 * 2. If a default UI language (e.g., English) matches the language code of a
 *    translation, the first matching translation is picked.
 * 3. If some translation has an unspecified language code, that translation is
 *    picked.
 * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
 * </pre>
 *
 * Protobuf type {@code transit_realtime.TranslatedImage}
 */
public final class TranslatedImage extends
    com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
      TranslatedImage> implements
    // @@protoc_insertion_point(message_implements:transit_realtime.TranslatedImage)
    TranslatedImageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TranslatedImage.newBuilder() to construct.
  private TranslatedImage(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.google.transit.realtime.TranslatedImage, ?> builder) {
    super(builder);
  }
  private TranslatedImage() {
    localizedImage_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TranslatedImage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.transit.realtime.TranslatedImage.class, com.google.transit.realtime.TranslatedImage.Builder.class);
  }

  public interface LocalizedImageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.TranslatedImage.LocalizedImage)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<LocalizedImage> {

    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return Whether the mediaType field is set.
     */
    boolean hasMediaType();
    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return The mediaType.
     */
    java.lang.String getMediaType();
    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return The bytes for mediaType.
     */
    com.google.protobuf.ByteString
        getMediaTypeBytes();

    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return Whether the language field is set.
     */
    boolean hasLanguage();
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.TranslatedImage.LocalizedImage}
   */
  public static final class LocalizedImage extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        LocalizedImage> implements
      // @@protoc_insertion_point(message_implements:transit_realtime.TranslatedImage.LocalizedImage)
      LocalizedImageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocalizedImage.newBuilder() to construct.
    private LocalizedImage(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.google.transit.realtime.TranslatedImage.LocalizedImage, ?> builder) {
      super(builder);
    }
    private LocalizedImage() {
      url_ = "";
      mediaType_ = "";
      language_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocalizedImage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_LocalizedImage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.TranslatedImage.LocalizedImage.class, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder.class);
    }

    private int bitField0_;
    public static final int URL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object url_ = "";
    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * String containing an URL linking to an image
     * The image linked must be less than 2MB. 
     * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
     * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
     * </pre>
     *
     * <code>required string url = 1;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEDIA_TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mediaType_ = "";
    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return Whether the mediaType field is set.
     */
    @java.lang.Override
    public boolean hasMediaType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return The mediaType.
     */
    @java.lang.Override
    public java.lang.String getMediaType() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mediaType_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * IANA media type as to specify the type of image to be displayed. 
     * The type must start with "image/"
     * </pre>
     *
     * <code>required string media_type = 2;</code>
     * @return The bytes for mediaType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaTypeBytes() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object language_ = "";
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return Whether the language field is set.
     */
    @java.lang.Override
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 3;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMediaType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<com.google.transit.realtime.TranslatedImage.LocalizedImage>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mediaType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, language_);
      }
      extensionWriter.writeUntil(10000, output);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mediaType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, language_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.transit.realtime.TranslatedImage.LocalizedImage)) {
        return super.equals(obj);
      }
      com.google.transit.realtime.TranslatedImage.LocalizedImage other = (com.google.transit.realtime.TranslatedImage.LocalizedImage) obj;

      if (hasUrl() != other.hasUrl()) return false;
      if (hasUrl()) {
        if (!getUrl()
            .equals(other.getUrl())) return false;
      }
      if (hasMediaType() != other.hasMediaType()) return false;
      if (hasMediaType()) {
        if (!getMediaType()
            .equals(other.getMediaType())) return false;
      }
      if (hasLanguage() != other.hasLanguage()) return false;
      if (hasLanguage()) {
        if (!getLanguage()
            .equals(other.getLanguage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      if (!getExtensionFields().equals(other.getExtensionFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUrl()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
      }
      if (hasMediaType()) {
        hash = (37 * hash) + MEDIA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMediaType().hashCode();
      }
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.TranslatedImage.LocalizedImage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.transit.realtime.TranslatedImage.LocalizedImage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.TranslatedImage.LocalizedImage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          com.google.transit.realtime.TranslatedImage.LocalizedImage, Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.TranslatedImage.LocalizedImage)
        com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_LocalizedImage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.TranslatedImage.LocalizedImage.class, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder.class);
      }

      // Construct using com.google.transit.realtime.TranslatedImage.LocalizedImage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        url_ = "";
        mediaType_ = "";
        language_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_LocalizedImage_descriptor;
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedImage.LocalizedImage getDefaultInstanceForType() {
        return com.google.transit.realtime.TranslatedImage.LocalizedImage.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedImage.LocalizedImage build() {
        com.google.transit.realtime.TranslatedImage.LocalizedImage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedImage.LocalizedImage buildPartial() {
        com.google.transit.realtime.TranslatedImage.LocalizedImage result = new com.google.transit.realtime.TranslatedImage.LocalizedImage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.transit.realtime.TranslatedImage.LocalizedImage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.url_ = url_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mediaType_ = mediaType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.language_ = language_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedImage.LocalizedImage, Type> extension,
          Type value) {
        return super.setExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedImage.LocalizedImage, java.util.List<Type>> extension,
          int index, Type value) {
        return super.setExtension(extension, index, value);
      }
      @java.lang.Override
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedImage.LocalizedImage, java.util.List<Type>> extension,
          Type value) {
        return super.addExtension(extension, value);
      }
      @java.lang.Override
      public <T> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedImage.LocalizedImage, T> extension) {
        return super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.TranslatedImage.LocalizedImage) {
          return mergeFrom((com.google.transit.realtime.TranslatedImage.LocalizedImage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.TranslatedImage.LocalizedImage other) {
        if (other == com.google.transit.realtime.TranslatedImage.LocalizedImage.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          url_ = other.url_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasMediaType()) {
          mediaType_ = other.mediaType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLanguage()) {
          language_ = other.language_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUrl()) {
          return false;
        }
        if (!hasMediaType()) {
          return false;
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                url_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mediaType_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                language_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object url_ = "";
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @return Whether the url field is set.
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        url_ = getDefaultInstance().getUrl();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String containing an URL linking to an image
       * The image linked must be less than 2MB. 
       * If an image changes in a significant enough way that an update is required on the consumer side, the producer must update the URL to a new one.
       * The URL should be a fully qualified URL that includes http:// or https://, and any special characters in the URL must be correctly escaped. See the following http://www.w3.org/Addressing/URL/4_URI_Recommentations.html for a description of how to create fully qualified URL values.
       * </pre>
       *
       * <code>required string url = 1;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object mediaType_ = "";
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @return Whether the mediaType field is set.
       */
      public boolean hasMediaType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @return The mediaType.
       */
      public java.lang.String getMediaType() {
        java.lang.Object ref = mediaType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mediaType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @return The bytes for mediaType.
       */
      public com.google.protobuf.ByteString
          getMediaTypeBytes() {
        java.lang.Object ref = mediaType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @param value The mediaType to set.
       * @return This builder for chaining.
       */
      public Builder setMediaType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mediaType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaType() {
        mediaType_ = getDefaultInstance().getMediaType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IANA media type as to specify the type of image to be displayed. 
       * The type must start with "image/"
       * </pre>
       *
       * <code>required string media_type = 2;</code>
       * @param value The bytes for mediaType to set.
       * @return This builder for chaining.
       */
      public Builder setMediaTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mediaType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @return Whether the language field is set.
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 3;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.TranslatedImage.LocalizedImage)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.TranslatedImage.LocalizedImage)
    private static final com.google.transit.realtime.TranslatedImage.LocalizedImage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.transit.realtime.TranslatedImage.LocalizedImage();
    }

    public static com.google.transit.realtime.TranslatedImage.LocalizedImage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LocalizedImage>
        PARSER = new com.google.protobuf.AbstractParser<LocalizedImage>() {
      @java.lang.Override
      public LocalizedImage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LocalizedImage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocalizedImage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedImage.LocalizedImage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int LOCALIZED_IMAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage> localizedImage_;
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage> getLocalizedImageList() {
    return localizedImage_;
  }
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder> 
      getLocalizedImageOrBuilderList() {
    return localizedImage_;
  }
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  @java.lang.Override
  public int getLocalizedImageCount() {
    return localizedImage_.size();
  }
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  @java.lang.Override
  public com.google.transit.realtime.TranslatedImage.LocalizedImage getLocalizedImage(int index) {
    return localizedImage_.get(index);
  }
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  @java.lang.Override
  public com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder getLocalizedImageOrBuilder(
      int index) {
    return localizedImage_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getLocalizedImageCount(); i++) {
      if (!getLocalizedImage(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .ExtendableMessage<com.google.transit.realtime.TranslatedImage>.ExtensionWriter
        extensionWriter = newExtensionWriter();
    for (int i = 0; i < localizedImage_.size(); i++) {
      output.writeMessage(1, localizedImage_.get(i));
    }
    extensionWriter.writeUntil(10000, output);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < localizedImage_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, localizedImage_.get(i));
    }
    size += extensionsSerializedSize();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.transit.realtime.TranslatedImage)) {
      return super.equals(obj);
    }
    com.google.transit.realtime.TranslatedImage other = (com.google.transit.realtime.TranslatedImage) obj;

    if (!getLocalizedImageList()
        .equals(other.getLocalizedImageList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    if (!getExtensionFields().equals(other.getExtensionFields()))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLocalizedImageCount() > 0) {
      hash = (37 * hash) + LOCALIZED_IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLocalizedImageList().hashCode();
    }
    hash = hashFields(hash, getExtensionFields());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.transit.realtime.TranslatedImage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.transit.realtime.TranslatedImage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.transit.realtime.TranslatedImage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.transit.realtime.TranslatedImage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.transit.realtime.TranslatedImage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * An internationalized image containing per-language versions of a URL linking to an image
   * along with meta information
   * Only one of the images from a message will be retained by consumers. The resolution proceeds
   * as follows:
   * 1. If the UI language matches the language code of a translation,
   *    the first matching translation is picked.
   * 2. If a default UI language (e.g., English) matches the language code of a
   *    translation, the first matching translation is picked.
   * 3. If some translation has an unspecified language code, that translation is
   *    picked.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
   * </pre>
   *
   * Protobuf type {@code transit_realtime.TranslatedImage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
        com.google.transit.realtime.TranslatedImage, Builder> implements
      // @@protoc_insertion_point(builder_implements:transit_realtime.TranslatedImage)
      com.google.transit.realtime.TranslatedImageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.TranslatedImage.class, com.google.transit.realtime.TranslatedImage.Builder.class);
    }

    // Construct using com.google.transit.realtime.TranslatedImage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (localizedImageBuilder_ == null) {
        localizedImage_ = java.util.Collections.emptyList();
      } else {
        localizedImage_ = null;
        localizedImageBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedImage_descriptor;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedImage getDefaultInstanceForType() {
      return com.google.transit.realtime.TranslatedImage.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedImage build() {
      com.google.transit.realtime.TranslatedImage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedImage buildPartial() {
      com.google.transit.realtime.TranslatedImage result = new com.google.transit.realtime.TranslatedImage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.transit.realtime.TranslatedImage result) {
      if (localizedImageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          localizedImage_ = java.util.Collections.unmodifiableList(localizedImage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.localizedImage_ = localizedImage_;
      } else {
        result.localizedImage_ = localizedImageBuilder_.build();
      }
    }

    private void buildPartial0(com.google.transit.realtime.TranslatedImage result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedImage, Type> extension,
        Type value) {
      return super.setExtension(extension, value);
    }
    @java.lang.Override
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedImage, java.util.List<Type>> extension,
        int index, Type value) {
      return super.setExtension(extension, index, value);
    }
    @java.lang.Override
    public <Type> Builder addExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedImage, java.util.List<Type>> extension,
        Type value) {
      return super.addExtension(extension, value);
    }
    @java.lang.Override
    public <T> Builder clearExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedImage, T> extension) {
      return super.clearExtension(extension);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.transit.realtime.TranslatedImage) {
        return mergeFrom((com.google.transit.realtime.TranslatedImage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.transit.realtime.TranslatedImage other) {
      if (other == com.google.transit.realtime.TranslatedImage.getDefaultInstance()) return this;
      if (localizedImageBuilder_ == null) {
        if (!other.localizedImage_.isEmpty()) {
          if (localizedImage_.isEmpty()) {
            localizedImage_ = other.localizedImage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLocalizedImageIsMutable();
            localizedImage_.addAll(other.localizedImage_);
          }
          onChanged();
        }
      } else {
        if (!other.localizedImage_.isEmpty()) {
          if (localizedImageBuilder_.isEmpty()) {
            localizedImageBuilder_.dispose();
            localizedImageBuilder_ = null;
            localizedImage_ = other.localizedImage_;
            bitField0_ = (bitField0_ & ~0x00000001);
            localizedImageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLocalizedImageFieldBuilder() : null;
          } else {
            localizedImageBuilder_.addAllMessages(other.localizedImage_);
          }
        }
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getLocalizedImageCount(); i++) {
        if (!getLocalizedImage(i).isInitialized()) {
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.transit.realtime.TranslatedImage.LocalizedImage m =
                  input.readMessage(
                      com.google.transit.realtime.TranslatedImage.LocalizedImage.PARSER,
                      extensionRegistry);
              if (localizedImageBuilder_ == null) {
                ensureLocalizedImageIsMutable();
                localizedImage_.add(m);
              } else {
                localizedImageBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage> localizedImage_ =
      java.util.Collections.emptyList();
    private void ensureLocalizedImageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        localizedImage_ = new java.util.ArrayList<com.google.transit.realtime.TranslatedImage.LocalizedImage>(localizedImage_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.transit.realtime.TranslatedImage.LocalizedImage, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder, com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder> localizedImageBuilder_;

    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage> getLocalizedImageList() {
      if (localizedImageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(localizedImage_);
      } else {
        return localizedImageBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public int getLocalizedImageCount() {
      if (localizedImageBuilder_ == null) {
        return localizedImage_.size();
      } else {
        return localizedImageBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public com.google.transit.realtime.TranslatedImage.LocalizedImage getLocalizedImage(int index) {
      if (localizedImageBuilder_ == null) {
        return localizedImage_.get(index);
      } else {
        return localizedImageBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder setLocalizedImage(
        int index, com.google.transit.realtime.TranslatedImage.LocalizedImage value) {
      if (localizedImageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedImageIsMutable();
        localizedImage_.set(index, value);
        onChanged();
      } else {
        localizedImageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder setLocalizedImage(
        int index, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder builderForValue) {
      if (localizedImageBuilder_ == null) {
        ensureLocalizedImageIsMutable();
        localizedImage_.set(index, builderForValue.build());
        onChanged();
      } else {
        localizedImageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder addLocalizedImage(com.google.transit.realtime.TranslatedImage.LocalizedImage value) {
      if (localizedImageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedImageIsMutable();
        localizedImage_.add(value);
        onChanged();
      } else {
        localizedImageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder addLocalizedImage(
        int index, com.google.transit.realtime.TranslatedImage.LocalizedImage value) {
      if (localizedImageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocalizedImageIsMutable();
        localizedImage_.add(index, value);
        onChanged();
      } else {
        localizedImageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder addLocalizedImage(
        com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder builderForValue) {
      if (localizedImageBuilder_ == null) {
        ensureLocalizedImageIsMutable();
        localizedImage_.add(builderForValue.build());
        onChanged();
      } else {
        localizedImageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder addLocalizedImage(
        int index, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder builderForValue) {
      if (localizedImageBuilder_ == null) {
        ensureLocalizedImageIsMutable();
        localizedImage_.add(index, builderForValue.build());
        onChanged();
      } else {
        localizedImageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder addAllLocalizedImage(
        java.lang.Iterable<? extends com.google.transit.realtime.TranslatedImage.LocalizedImage> values) {
      if (localizedImageBuilder_ == null) {
        ensureLocalizedImageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, localizedImage_);
        onChanged();
      } else {
        localizedImageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder clearLocalizedImage() {
      if (localizedImageBuilder_ == null) {
        localizedImage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        localizedImageBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public Builder removeLocalizedImage(int index) {
      if (localizedImageBuilder_ == null) {
        ensureLocalizedImageIsMutable();
        localizedImage_.remove(index);
        onChanged();
      } else {
        localizedImageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder getLocalizedImageBuilder(
        int index) {
      return getLocalizedImageFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder getLocalizedImageOrBuilder(
        int index) {
      if (localizedImageBuilder_ == null) {
        return localizedImage_.get(index);  } else {
        return localizedImageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public java.util.List<? extends com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder> 
         getLocalizedImageOrBuilderList() {
      if (localizedImageBuilder_ != null) {
        return localizedImageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(localizedImage_);
      }
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder addLocalizedImageBuilder() {
      return getLocalizedImageFieldBuilder().addBuilder(
          com.google.transit.realtime.TranslatedImage.LocalizedImage.getDefaultInstance());
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder addLocalizedImageBuilder(
        int index) {
      return getLocalizedImageFieldBuilder().addBuilder(
          index, com.google.transit.realtime.TranslatedImage.LocalizedImage.getDefaultInstance());
    }
    /**
     * <pre>
     * At least one localized image must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
     */
    public java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder> 
         getLocalizedImageBuilderList() {
      return getLocalizedImageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.transit.realtime.TranslatedImage.LocalizedImage, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder, com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder> 
        getLocalizedImageFieldBuilder() {
      if (localizedImageBuilder_ == null) {
        localizedImageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.transit.realtime.TranslatedImage.LocalizedImage, com.google.transit.realtime.TranslatedImage.LocalizedImage.Builder, com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder>(
                localizedImage_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        localizedImage_ = null;
      }
      return localizedImageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transit_realtime.TranslatedImage)
  }

  // @@protoc_insertion_point(class_scope:transit_realtime.TranslatedImage)
  private static final com.google.transit.realtime.TranslatedImage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.transit.realtime.TranslatedImage();
  }

  public static com.google.transit.realtime.TranslatedImage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TranslatedImage>
      PARSER = new com.google.protobuf.AbstractParser<TranslatedImage>() {
    @java.lang.Override
    public TranslatedImage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TranslatedImage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TranslatedImage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.transit.realtime.TranslatedImage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

