// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

/**
 * <pre>
 * An internationalized message containing per-language versions of a snippet of
 * text or a URL.
 * One of the strings from a message will be picked up. The resolution proceeds
 * as follows:
 * 1. If the UI language matches the language code of a translation,
 *    the first matching translation is picked.
 * 2. If a default UI language (e.g., English) matches the language code of a
 *    translation, the first matching translation is picked.
 * 3. If some translation has an unspecified language code, that translation is
 *    picked.
 * </pre>
 *
 * Protobuf type {@code transit_realtime.TranslatedString}
 */
public final class TranslatedString extends
    com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
      TranslatedString> implements
    // @@protoc_insertion_point(message_implements:transit_realtime.TranslatedString)
    TranslatedStringOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TranslatedString.newBuilder() to construct.
  private TranslatedString(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.google.transit.realtime.TranslatedString, ?> builder) {
    super(builder);
  }
  private TranslatedString() {
    translation_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TranslatedString();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.transit.realtime.TranslatedString.class, com.google.transit.realtime.TranslatedString.Builder.class);
  }

  public interface TranslationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.TranslatedString.Translation)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Translation> {

    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return Whether the text field is set.
     */
    boolean hasText();
    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return Whether the language field is set.
     */
    boolean hasLanguage();
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.TranslatedString.Translation}
   */
  public static final class Translation extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Translation> implements
      // @@protoc_insertion_point(message_implements:transit_realtime.TranslatedString.Translation)
      TranslationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Translation.newBuilder() to construct.
    private Translation(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.google.transit.realtime.TranslatedString.Translation, ?> builder) {
      super(builder);
    }
    private Translation() {
      text_ = "";
      language_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Translation();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_Translation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.TranslatedString.Translation.class, com.google.transit.realtime.TranslatedString.Translation.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A UTF-8 string containing the message.
     * </pre>
     *
     * <code>required string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object language_ = "";
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return Whether the language field is set.
     */
    @java.lang.Override
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * BCP-47 language code. Can be omitted if the language is unknown or if
     * no i18n is done at all for the feed. At most one translation is
     * allowed to have an unspecified language tag.
     * </pre>
     *
     * <code>optional string language = 2;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<com.google.transit.realtime.TranslatedString.Translation>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
      }
      extensionWriter.writeUntil(10000, output);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.transit.realtime.TranslatedString.Translation)) {
        return super.equals(obj);
      }
      com.google.transit.realtime.TranslatedString.Translation other = (com.google.transit.realtime.TranslatedString.Translation) obj;

      if (hasText() != other.hasText()) return false;
      if (hasText()) {
        if (!getText()
            .equals(other.getText())) return false;
      }
      if (hasLanguage() != other.hasLanguage()) return false;
      if (hasLanguage()) {
        if (!getLanguage()
            .equals(other.getLanguage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      if (!getExtensionFields().equals(other.getExtensionFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.transit.realtime.TranslatedString.Translation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.transit.realtime.TranslatedString.Translation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.transit.realtime.TranslatedString.Translation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.transit.realtime.TranslatedString.Translation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.TranslatedString.Translation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          com.google.transit.realtime.TranslatedString.Translation, Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.TranslatedString.Translation)
        com.google.transit.realtime.TranslatedString.TranslationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_Translation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.transit.realtime.TranslatedString.Translation.class, com.google.transit.realtime.TranslatedString.Translation.Builder.class);
      }

      // Construct using com.google.transit.realtime.TranslatedString.Translation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        language_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_Translation_descriptor;
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedString.Translation getDefaultInstanceForType() {
        return com.google.transit.realtime.TranslatedString.Translation.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedString.Translation build() {
        com.google.transit.realtime.TranslatedString.Translation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.transit.realtime.TranslatedString.Translation buildPartial() {
        com.google.transit.realtime.TranslatedString.Translation result = new com.google.transit.realtime.TranslatedString.Translation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.transit.realtime.TranslatedString.Translation result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.language_ = language_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedString.Translation, Type> extension,
          Type value) {
        return super.setExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedString.Translation, java.util.List<Type>> extension,
          int index, Type value) {
        return super.setExtension(extension, index, value);
      }
      @java.lang.Override
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedString.Translation, java.util.List<Type>> extension,
          Type value) {
        return super.addExtension(extension, value);
      }
      @java.lang.Override
      public <T> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.google.transit.realtime.TranslatedString.Translation, T> extension) {
        return super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.transit.realtime.TranslatedString.Translation) {
          return mergeFrom((com.google.transit.realtime.TranslatedString.Translation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.transit.realtime.TranslatedString.Translation other) {
        if (other == com.google.transit.realtime.TranslatedString.Translation.getDefaultInstance()) return this;
        if (other.hasText()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasLanguage()) {
          language_ = other.language_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasText()) {
          return false;
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                language_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @return Whether the text field is set.
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A UTF-8 string containing the message.
       * </pre>
       *
       * <code>required string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @return Whether the language field is set.
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BCP-47 language code. Can be omitted if the language is unknown or if
       * no i18n is done at all for the feed. At most one translation is
       * allowed to have an unspecified language tag.
       * </pre>
       *
       * <code>optional string language = 2;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.TranslatedString.Translation)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.TranslatedString.Translation)
    private static final com.google.transit.realtime.TranslatedString.Translation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.transit.realtime.TranslatedString.Translation();
    }

    public static com.google.transit.realtime.TranslatedString.Translation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Translation>
        PARSER = new com.google.protobuf.AbstractParser<Translation>() {
      @java.lang.Override
      public Translation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Translation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Translation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedString.Translation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TRANSLATION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.transit.realtime.TranslatedString.Translation> translation_;
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.transit.realtime.TranslatedString.Translation> getTranslationList() {
    return translation_;
  }
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.transit.realtime.TranslatedString.TranslationOrBuilder> 
      getTranslationOrBuilderList() {
    return translation_;
  }
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  @java.lang.Override
  public int getTranslationCount() {
    return translation_.size();
  }
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  @java.lang.Override
  public com.google.transit.realtime.TranslatedString.Translation getTranslation(int index) {
    return translation_.get(index);
  }
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  @java.lang.Override
  public com.google.transit.realtime.TranslatedString.TranslationOrBuilder getTranslationOrBuilder(
      int index) {
    return translation_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getTranslationCount(); i++) {
      if (!getTranslation(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .ExtendableMessage<com.google.transit.realtime.TranslatedString>.ExtensionWriter
        extensionWriter = newExtensionWriter();
    for (int i = 0; i < translation_.size(); i++) {
      output.writeMessage(1, translation_.get(i));
    }
    extensionWriter.writeUntil(10000, output);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < translation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, translation_.get(i));
    }
    size += extensionsSerializedSize();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.transit.realtime.TranslatedString)) {
      return super.equals(obj);
    }
    com.google.transit.realtime.TranslatedString other = (com.google.transit.realtime.TranslatedString) obj;

    if (!getTranslationList()
        .equals(other.getTranslationList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    if (!getExtensionFields().equals(other.getExtensionFields()))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTranslationCount() > 0) {
      hash = (37 * hash) + TRANSLATION_FIELD_NUMBER;
      hash = (53 * hash) + getTranslationList().hashCode();
    }
    hash = hashFields(hash, getExtensionFields());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.transit.realtime.TranslatedString parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.transit.realtime.TranslatedString parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.transit.realtime.TranslatedString parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.transit.realtime.TranslatedString parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.transit.realtime.TranslatedString prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * An internationalized message containing per-language versions of a snippet of
   * text or a URL.
   * One of the strings from a message will be picked up. The resolution proceeds
   * as follows:
   * 1. If the UI language matches the language code of a translation,
   *    the first matching translation is picked.
   * 2. If a default UI language (e.g., English) matches the language code of a
   *    translation, the first matching translation is picked.
   * 3. If some translation has an unspecified language code, that translation is
   *    picked.
   * </pre>
   *
   * Protobuf type {@code transit_realtime.TranslatedString}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
        com.google.transit.realtime.TranslatedString, Builder> implements
      // @@protoc_insertion_point(builder_implements:transit_realtime.TranslatedString)
      com.google.transit.realtime.TranslatedStringOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.transit.realtime.TranslatedString.class, com.google.transit.realtime.TranslatedString.Builder.class);
    }

    // Construct using com.google.transit.realtime.TranslatedString.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (translationBuilder_ == null) {
        translation_ = java.util.Collections.emptyList();
      } else {
        translation_ = null;
        translationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.transit.realtime.GtfsRealtime.internal_static_transit_realtime_TranslatedString_descriptor;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedString getDefaultInstanceForType() {
      return com.google.transit.realtime.TranslatedString.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedString build() {
      com.google.transit.realtime.TranslatedString result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.transit.realtime.TranslatedString buildPartial() {
      com.google.transit.realtime.TranslatedString result = new com.google.transit.realtime.TranslatedString(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.transit.realtime.TranslatedString result) {
      if (translationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          translation_ = java.util.Collections.unmodifiableList(translation_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.translation_ = translation_;
      } else {
        result.translation_ = translationBuilder_.build();
      }
    }

    private void buildPartial0(com.google.transit.realtime.TranslatedString result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedString, Type> extension,
        Type value) {
      return super.setExtension(extension, value);
    }
    @java.lang.Override
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedString, java.util.List<Type>> extension,
        int index, Type value) {
      return super.setExtension(extension, index, value);
    }
    @java.lang.Override
    public <Type> Builder addExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedString, java.util.List<Type>> extension,
        Type value) {
      return super.addExtension(extension, value);
    }
    @java.lang.Override
    public <T> Builder clearExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            com.google.transit.realtime.TranslatedString, T> extension) {
      return super.clearExtension(extension);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.transit.realtime.TranslatedString) {
        return mergeFrom((com.google.transit.realtime.TranslatedString)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.transit.realtime.TranslatedString other) {
      if (other == com.google.transit.realtime.TranslatedString.getDefaultInstance()) return this;
      if (translationBuilder_ == null) {
        if (!other.translation_.isEmpty()) {
          if (translation_.isEmpty()) {
            translation_ = other.translation_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTranslationIsMutable();
            translation_.addAll(other.translation_);
          }
          onChanged();
        }
      } else {
        if (!other.translation_.isEmpty()) {
          if (translationBuilder_.isEmpty()) {
            translationBuilder_.dispose();
            translationBuilder_ = null;
            translation_ = other.translation_;
            bitField0_ = (bitField0_ & ~0x00000001);
            translationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTranslationFieldBuilder() : null;
          } else {
            translationBuilder_.addAllMessages(other.translation_);
          }
        }
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getTranslationCount(); i++) {
        if (!getTranslation(i).isInitialized()) {
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.transit.realtime.TranslatedString.Translation m =
                  input.readMessage(
                      com.google.transit.realtime.TranslatedString.Translation.PARSER,
                      extensionRegistry);
              if (translationBuilder_ == null) {
                ensureTranslationIsMutable();
                translation_.add(m);
              } else {
                translationBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.transit.realtime.TranslatedString.Translation> translation_ =
      java.util.Collections.emptyList();
    private void ensureTranslationIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        translation_ = new java.util.ArrayList<com.google.transit.realtime.TranslatedString.Translation>(translation_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.transit.realtime.TranslatedString.Translation, com.google.transit.realtime.TranslatedString.Translation.Builder, com.google.transit.realtime.TranslatedString.TranslationOrBuilder> translationBuilder_;

    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public java.util.List<com.google.transit.realtime.TranslatedString.Translation> getTranslationList() {
      if (translationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(translation_);
      } else {
        return translationBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public int getTranslationCount() {
      if (translationBuilder_ == null) {
        return translation_.size();
      } else {
        return translationBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public com.google.transit.realtime.TranslatedString.Translation getTranslation(int index) {
      if (translationBuilder_ == null) {
        return translation_.get(index);
      } else {
        return translationBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder setTranslation(
        int index, com.google.transit.realtime.TranslatedString.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.set(index, value);
        onChanged();
      } else {
        translationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder setTranslation(
        int index, com.google.transit.realtime.TranslatedString.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.set(index, builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder addTranslation(com.google.transit.realtime.TranslatedString.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.add(value);
        onChanged();
      } else {
        translationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder addTranslation(
        int index, com.google.transit.realtime.TranslatedString.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.add(index, value);
        onChanged();
      } else {
        translationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder addTranslation(
        com.google.transit.realtime.TranslatedString.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.add(builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder addTranslation(
        int index, com.google.transit.realtime.TranslatedString.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.add(index, builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder addAllTranslation(
        java.lang.Iterable<? extends com.google.transit.realtime.TranslatedString.Translation> values) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, translation_);
        onChanged();
      } else {
        translationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder clearTranslation() {
      if (translationBuilder_ == null) {
        translation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        translationBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public Builder removeTranslation(int index) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.remove(index);
        onChanged();
      } else {
        translationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public com.google.transit.realtime.TranslatedString.Translation.Builder getTranslationBuilder(
        int index) {
      return getTranslationFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public com.google.transit.realtime.TranslatedString.TranslationOrBuilder getTranslationOrBuilder(
        int index) {
      if (translationBuilder_ == null) {
        return translation_.get(index);  } else {
        return translationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public java.util.List<? extends com.google.transit.realtime.TranslatedString.TranslationOrBuilder> 
         getTranslationOrBuilderList() {
      if (translationBuilder_ != null) {
        return translationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(translation_);
      }
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public com.google.transit.realtime.TranslatedString.Translation.Builder addTranslationBuilder() {
      return getTranslationFieldBuilder().addBuilder(
          com.google.transit.realtime.TranslatedString.Translation.getDefaultInstance());
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public com.google.transit.realtime.TranslatedString.Translation.Builder addTranslationBuilder(
        int index) {
      return getTranslationFieldBuilder().addBuilder(
          index, com.google.transit.realtime.TranslatedString.Translation.getDefaultInstance());
    }
    /**
     * <pre>
     * At least one translation must be provided.
     * </pre>
     *
     * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
     */
    public java.util.List<com.google.transit.realtime.TranslatedString.Translation.Builder> 
         getTranslationBuilderList() {
      return getTranslationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.transit.realtime.TranslatedString.Translation, com.google.transit.realtime.TranslatedString.Translation.Builder, com.google.transit.realtime.TranslatedString.TranslationOrBuilder> 
        getTranslationFieldBuilder() {
      if (translationBuilder_ == null) {
        translationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.transit.realtime.TranslatedString.Translation, com.google.transit.realtime.TranslatedString.Translation.Builder, com.google.transit.realtime.TranslatedString.TranslationOrBuilder>(
                translation_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        translation_ = null;
      }
      return translationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transit_realtime.TranslatedString)
  }

  // @@protoc_insertion_point(class_scope:transit_realtime.TranslatedString)
  private static final com.google.transit.realtime.TranslatedString DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.transit.realtime.TranslatedString();
  }

  public static com.google.transit.realtime.TranslatedString getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TranslatedString>
      PARSER = new com.google.protobuf.AbstractParser<TranslatedString>() {
    @java.lang.Override
    public TranslatedString parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TranslatedString> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TranslatedString> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.transit.realtime.TranslatedString getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

