// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface TranslatedImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.TranslatedImage)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<TranslatedImage> {

  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  java.util.List<com.google.transit.realtime.TranslatedImage.LocalizedImage> 
      getLocalizedImageList();
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  com.google.transit.realtime.TranslatedImage.LocalizedImage getLocalizedImage(int index);
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  int getLocalizedImageCount();
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  java.util.List<? extends com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder> 
      getLocalizedImageOrBuilderList();
  /**
   * <pre>
   * At least one localized image must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedImage.LocalizedImage localized_image = 1;</code>
   */
  com.google.transit.realtime.TranslatedImage.LocalizedImageOrBuilder getLocalizedImageOrBuilder(
      int index);
}
