// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/gtfs-realtime.proto

package com.google.transit.realtime;

public interface TranslatedStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.TranslatedString)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<TranslatedString> {

  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  java.util.List<com.google.transit.realtime.TranslatedString.Translation> 
      getTranslationList();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  com.google.transit.realtime.TranslatedString.Translation getTranslation(int index);
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  int getTranslationCount();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  java.util.List<? extends com.google.transit.realtime.TranslatedString.TranslationOrBuilder> 
      getTranslationOrBuilderList();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  com.google.transit.realtime.TranslatedString.TranslationOrBuilder getTranslationOrBuilder(
      int index);
}
